<?php

/* custom routes generated by CRUD */


// Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.products.'), function () {

//     Route::get('products', ['as'=> 'index', 'uses' => 'ProductController@index']);
//     Route::post('products', ['as'=> 'store', 'uses' => 'ProductController@store']);
//     Route::get('products/create', ['as'=> 'create', 'uses' => 'ProductController@create']);
//     Route::put('products/{products}', ['as'=> 'update', 'uses' => 'ProductController@update']);
//     Route::get('products/{id}/delete', array('as' => 'delete', 'uses' => 'ProductController@getDelete'));
//     Route::get('products/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'ProductController@getModalDelete'));
//     Route::get('products/{products}', ['as'=> 'show', 'uses' => 'ProductController@show']);
//     Route::get('products/{products}/edit', ['as'=> 'edit', 'uses' => 'ProductController@edit']);
//     Route::post('products/upload', ['as' => 'upload', 'uses' => 'ProductController@uploadProductExcel']);

//     // Zone Price
//     Route::get('products/{id}/zonePrices', ['as' => 'getZonePrices', 'uses' => 'ProductController@getZonePrices']);
//     Route::post('products/{id}/create/zonePrice', ['as' => 'createZonePrice', 'uses' => 'ProductController@createZonePrice']);

//     //Ajax Call
//     Route::get('getProduct/{id}', 'ProductController@getProduct');

// });

Route::group(array('prefix' => 'admin/', 'middleware' => 'auth', 'namespace' => 'Admin', 'as'=>'admin.customers.'), function () {

    Route::get('customers', ['as'=> 'index', 'uses' => 'CustomerController@index']);
    Route::post('customers', ['as'=> 'store', 'uses' => 'CustomerController@store']);
    Route::get('customers/create', ['as'=> 'create', 'uses' => 'CustomerController@create']);
    Route::put('customers/{customers}', ['as'=> 'update', 'uses' => 'CustomerController@update']);
    Route::patch('customers/{customers}', ['as'=> 'update', 'uses' => 'CustomerController@update']);
    Route::get('customers/{id}/delete', array('as' => 'delete', 'uses' => 'CustomerController@getDelete'));
    Route::get('customers/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'CustomerController@getModalDelete'));
    Route::get('customers/{customers}', ['as'=> 'show', 'uses' => 'CustomerController@show']);
    Route::get('customers/{customers}/edit', ['as'=> 'edit', 'uses' => 'CustomerController@edit']);

});


// Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'auth','as'=>'admin.banners.'), function () {

//     Route::get('banners', ['as'=> 'index', 'uses' => 'BannerController@index']);
//     Route::post('banners', ['as'=> 'store', 'uses' => 'BannerController@store']);
//     Route::get('banners/create', ['as'=> 'create', 'uses' => 'BannerController@create']);
//     Route::put('banners/{banners}', ['as'=> 'update', 'uses' => 'BannerController@update']);
//     Route::patch('banners/{banners}', ['as'=> 'update', 'uses' => 'BannerController@update']);
//     Route::get('banners/{id}/delete', array('as' => 'delete', 'uses' => 'BannerController@getDelete'));
//     Route::get('banners/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'BannerController@getModalDelete'));
//     Route::get('banners/{banners}', ['as'=> 'show', 'uses' => 'BannerController@show']);
//     Route::get('banners/{banners}/edit', ['as'=> 'edit', 'uses' => 'BannerController@edit']);

// });






// Route::group(array('prefix' => 'admin/testMaster/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.testMaster.'), function () {

// Route::get('testModels', ['as'=> 'testModels.index', 'uses' => 'Testmaster\TestModelController@index']);
// Route::post('testModels', ['as'=> 'testModels.store', 'uses' => 'Testmaster\TestModelController@store']);
// Route::get('testModels/create', ['as'=> 'testModels.create', 'uses' => 'Testmaster\TestModelController@create']);
// Route::put('testModels/{testModels}', ['as'=> 'testModels.update', 'uses' => 'Testmaster\TestModelController@update']);
// Route::patch('testModels/{testModels}', ['as'=> 'testModels.update', 'uses' => 'Testmaster\TestModelController@update']);
// Route::get('testModels/{id}/delete', array('as' => 'testModels.delete', 'uses' => 'Testmaster\TestModelController@getDelete'));
// Route::get('testModels/{id}/confirm-delete', array('as' => 'testModels.confirm-delete', 'uses' => 'Testmaster\TestModelController@getModalDelete'));
// Route::get('testModels/{testModels}', ['as'=> 'testModels.show', 'uses' => 'Testmaster\TestModelController@show']);
// Route::get('testModels/{testModels}/edit', ['as'=> 'testModels.edit', 'uses' => 'Testmaster\TestModelController@edit']);

// });

Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.productNetOnes.'), function () {

// Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'auth','as'=>'admin.productNetOnes'), function () {

Route::get('productNetOnes', ['as'=> 'index', 'uses' => 'ProductNetOneController@index']);
Route::post('productNetOnes', ['as'=> 'store', 'uses' => 'ProductNetOneController@store']);
Route::post('productNetOnes', ['as'=> 'reload', 'uses' => 'ProductNetOneController@reload']);
Route::get('productNetOnes/reload', ['as'=> 'reload', 'uses' => 'ProductNetOneController@reload']);
Route::get('productNetOnes/create', ['as'=> 'create', 'uses' => 'ProductNetOneController@create']);
Route::put('productNetOnes/{productNetOnes}', ['as'=> 'update', 'uses' => 'ProductNetOneController@update']);
Route::patch('productNetOnes/{productNetOnes}', ['as'=> 'update', 'uses' => 'ProductNetOneController@update']);
Route::get('productNetOnes/{id}/delete', array('as' => 'delete', 'uses' => 'ProductNetOneController@getDelete'));
Route::get('productNetOnes/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'ProductNetOneController@getModalDelete'));
Route::get('productNetOnes/{productNetOnes}', ['as'=> 'show', 'uses' => 'ProductNetOneController@show']);
Route::get('productNetOnes/{productNetOnes}/edit', ['as'=> 'edit', 'uses' => 'ProductNetOneController@edit']);

Route::post('productNetOnes/upload', ['as' => 'upload', 'uses' => 'ProductNetOneController@uploadAsExcel']);
});




Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.'), function () {
// Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.bannerNetones.'), function () {

Route::get('bannerNetones', ['as'=> 'bannerNetones.index', 'uses' => 'BannerNetoneController@index']);
Route::post('bannerNetones', ['as'=> 'bannerNetones.store', 'uses' => 'BannerNetoneController@store']);
Route::get('bannerNetones/create', ['as'=> 'bannerNetones.create', 'uses' => 'BannerNetoneController@create']);
Route::put('bannerNetones/{bannerNetones}', ['as'=> 'bannerNetones.update', 'uses' => 'BannerNetoneController@update']);
Route::patch('bannerNetones/{bannerNetones}', ['as'=> 'bannerNetones.update', 'uses' => 'BannerNetoneController@update']);
Route::get('bannerNetones/{id}/delete', array('as' => 'bannerNetones.delete', 'uses' => 'BannerNetoneController@getDelete'));
Route::get('bannerNetones/{id}/confirm-delete', array('as' => 'bannerNetones.confirm-delete', 'uses' => 'BannerNetoneController@getModalDelete'));
Route::get('bannerNetones/{bannerNetones}', ['as'=> 'bannerNetones.show', 'uses' => 'BannerNetoneController@show']);
Route::get('bannerNetones/{bannerNetones}/edit', ['as'=> 'bannerNetones.edit', 'uses' => 'BannerNetoneController@edit']);
});


// Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {
    Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.'), function () {
Route::get('devicesNetOnes', ['as'=> 'devicesNetOnes.index', 'uses' => 'DevicesNetOneController@index']);
Route::post('devicesNetOnes', ['as'=> 'devicesNetOnes.store', 'uses' => 'DevicesNetOneController@store']);
Route::get('devicesNetOnes/create', ['as'=> 'devicesNetOnes.create', 'uses' => 'DevicesNetOneController@create']);
Route::put('devicesNetOnes/{devicesNetOnes}', ['as'=> 'devicesNetOnes.update', 'uses' => 'DevicesNetOneController@update']);
Route::patch('devicesNetOnes/{devicesNetOnes}', ['as'=> 'devicesNetOnes.update', 'uses' => 'DevicesNetOneController@update']);
Route::get('devicesNetOnes/{id}/delete', array('as' => 'devicesNetOnes.delete', 'uses' => 'DevicesNetOneController@getDelete'));
Route::get('devicesNetOnes/{id}/confirm-delete', array('as' => 'devicesNetOnes.confirm-delete', 'uses' => 'DevicesNetOneController@getModalDelete'));
Route::get('devicesNetOnes/{devicesNetOnes}', ['as'=> 'devicesNetOnes.show', 'uses' => 'DevicesNetOneController@show']);
Route::get('devicesNetOnes/{devicesNetOnes}/edit', ['as'=> 'devicesNetOnes.edit', 'uses' => 'DevicesNetOneController@edit']);

});

Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.'), function () {

Route::get('rewards', ['as'=> 'rewards.index', 'uses' => 'RewardController@index']);
Route::post('rewards', ['as'=> 'rewards.store', 'uses' => 'RewardController@store']);
Route::get('rewards/create', ['as'=> 'rewards.create', 'uses' => 'RewardController@create']);
Route::put('rewards/{rewards}', ['as'=> 'rewards.update', 'uses' => 'RewardController@update']);
Route::patch('rewards/{rewards}', ['as'=> 'rewards.update', 'uses' => 'RewardController@update']);
Route::get('rewards/{id}/delete', array('as' => 'rewards.delete', 'uses' => 'RewardController@getDelete'));
Route::get('rewards/{id}/confirm-delete', array('as' => 'rewards.confirm-delete', 'uses' => 'RewardController@getModalDelete'));
Route::get('rewards/{rewards}', ['as'=> 'rewards.show', 'uses' => 'RewardController@show']);
Route::get('rewards/{rewards}/edit', ['as'=> 'rewards.edit', 'uses' => 'RewardController@edit']);

Route::post('rewards/upload', ['as' => 'rewards.upload', 'uses' => 'RewardController@uploadAsExcel']);
});
