<?php

/* custom routes generated by CRUD */


Route::group(array('middleware' => 'auth', 'prefix' => 'admin/' ,'namespace' => 'Admin','as'=>'admin.products.'), function () {

    Route::get('products', ['as'=> 'index', 'uses' => 'ProductController@index']);
    Route::post('products', ['as'=> 'store', 'uses' => 'ProductController@store']);
    Route::get('products/create', ['as'=> 'create', 'uses' => 'ProductController@create']);
    Route::put('products/{products}', ['as'=> 'update', 'uses' => 'ProductController@update']);
    Route::get('products/{id}/delete', array('as' => 'delete', 'uses' => 'ProductController@getDelete'));
    Route::get('products/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'ProductController@getModalDelete'));
    Route::get('products/{products}', ['as'=> 'show', 'uses' => 'ProductController@show']);
    Route::get('products/{products}/edit', ['as'=> 'edit', 'uses' => 'ProductController@edit']);
    Route::post('products/upload', ['as' => 'upload', 'uses' => 'ProductController@uploadProductExcel']);

    // Zone Price
    Route::get('products/{id}/zonePrices', ['as' => 'getZonePrices', 'uses' => 'ProductController@getZonePrices']);
    Route::post('products/{id}/create/zonePrice', ['as' => 'createZonePrice', 'uses' => 'ProductController@createZonePrice']);

    //Ajax Call
    Route::get('getProduct/{id}', 'ProductController@getProduct');

});

Route::group(array('prefix' => 'admin/', 'middleware' => 'auth', 'namespace' => 'Admin', 'as'=>'admin.customers.'), function () {

    Route::get('customers', ['as'=> 'index', 'uses' => 'CustomerController@index']);
    Route::post('customers', ['as'=> 'store', 'uses' => 'CustomerController@store']);
    Route::get('customers/create', ['as'=> 'create', 'uses' => 'CustomerController@create']);
    Route::put('customers/{customers}', ['as'=> 'update', 'uses' => 'CustomerController@update']);
    Route::patch('customers/{customers}', ['as'=> 'update', 'uses' => 'CustomerController@update']);
    Route::get('customers/{id}/delete', array('as' => 'delete', 'uses' => 'CustomerController@getDelete'));
    Route::get('customers/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'CustomerController@getModalDelete'));
    Route::get('customers/{customers}', ['as'=> 'show', 'uses' => 'CustomerController@show']);
    Route::get('customers/{customers}/edit', ['as'=> 'edit', 'uses' => 'CustomerController@edit']);

});


Route::group(array('prefix' => 'admin/', 'namespace' => 'Admin', 'middleware' => 'auth', 'as'=>'admin.productTypes.'), function () {

    Route::get('productTypes', ['as'=> 'index', 'uses' => 'ProductTypeController@index']);
    Route::post('productTypes', ['as'=> 'store', 'uses' => 'ProductTypeController@store']);
    Route::get('productTypes/create', ['as'=> 'create', 'uses' => 'ProductTypeController@create']);
    Route::put('productTypes/{productTypes}', ['as'=> 'update', 'uses' => 'ProductTypeController@update']);
    Route::patch('productTypes/{productTypes}', ['as'=> 'update', 'uses' => 'ProductTypeController@update']);
    Route::get('productTypes/{id}/delete', array('as' => 'delete', 'uses' => 'ProductTypeController@getDelete'));
    Route::get('productTypes/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'ProductTypeController@getModalDelete'));
    Route::get('productTypes/{productTypes}', ['as'=> 'show', 'uses' => 'ProductTypeController@show']);
    Route::get('productTypes/{productTypes}/edit', ['as'=> 'edit', 'uses' => 'ProductTypeController@edit']);

});

Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'auth','as'=>'admin.banners.'), function () {

    Route::get('banners', ['as'=> 'index', 'uses' => 'BannerController@index']);
    Route::post('banners', ['as'=> 'store', 'uses' => 'BannerController@store']);
    Route::get('banners/create', ['as'=> 'create', 'uses' => 'BannerController@create']);
    Route::put('banners/{banners}', ['as'=> 'update', 'uses' => 'BannerController@update']);
    Route::patch('banners/{banners}', ['as'=> 'update', 'uses' => 'BannerController@update']);
    Route::get('banners/{id}/delete', array('as' => 'delete', 'uses' => 'BannerController@getDelete'));
    Route::get('banners/{id}/confirm-delete', array('as' => 'confirm-delete', 'uses' => 'BannerController@getModalDelete'));
    Route::get('banners/{banners}', ['as'=> 'show', 'uses' => 'BannerController@show']);
    Route::get('banners/{banners}/edit', ['as'=> 'edit', 'uses' => 'BannerController@edit']);

});

// Route::group(array('prefix' => 'admin/zonePrice/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.zonePrice.'), function () {

// Route::get('zonePrices', ['as'=> 'zonePrices.index', 'uses' => 'ZonePrices\ZonePriceController@index']);
// Route::post('zonePrices', ['as'=> 'zonePrices.store', 'uses' => 'ZonePrices\ZonePriceController@store']);
// Route::get('zonePrices/create', ['as'=> 'zonePrices.create', 'uses' => 'ZonePrices\ZonePriceController@create']);
// Route::put('zonePrices/{zonePrices}', ['as'=> 'zonePrices.update', 'uses' => 'ZonePrices\ZonePriceController@update']);
// Route::patch('zonePrices/{zonePrices}', ['as'=> 'zonePrices.update', 'uses' => 'ZonePrices\ZonePriceController@update']);
// Route::get('zonePrices/{id}/delete', array('as' => 'zonePrices.delete', 'uses' => 'ZonePrices\ZonePriceController@getDelete'));
// Route::get('zonePrices/{id}/confirm-delete', array('as' => 'zonePrices.confirm-delete', 'uses' => 'ZonePrices\ZonePriceController@getModalDelete'));
// Route::get('zonePrices/{zonePrices}', ['as'=> 'zonePrices.show', 'uses' => 'ZonePrices\ZonePriceController@show']);
// Route::get('zonePrices/{zonePrices}/edit', ['as'=> 'zonePrices.edit', 'uses' => 'ZonePrices\ZonePriceController@edit']);

// });


